export const data = JSON.parse("{\"key\":\"v-2a277b14\",\"path\":\"/posts/reactor/reactor%E6%A8%A1%E5%BC%8F%20copy.html\",\"title\":\"Reactor模式解析及java实现\",\"lang\":\"en-US\",\"frontmatter\":{\"icon\":\"edit\",\"date\":\"2022-11-23T00:00:00.000Z\",\"category\":[\"响应式编程\"],\"tag\":[\"reactor\",\"nio\"],\"description\":\"周末看到徐昊老师在极客时间上的《如何使用Smart Domain实现DDD》 (https://www.bilibili.com/video/BV1QT411J7jh?mid=349471258&p=1&sharefrom=ugc&sharemedium=iphone&shareplat=ios&sharesessionid=AE38A38A-25FE...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://pc-dong.github.io/posts/reactor/reactor%E6%A8%A1%E5%BC%8F%20copy.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"PC-Dong\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Reactor模式解析及java实现\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"周末看到徐昊老师在极客时间上的《如何使用Smart Domain实现DDD》 (https://www.bilibili.com/video/BV1QT411J7jh?mid=349471258&p=1&sharefrom=ugc&sharemedium=iphone&shareplat=ios&sharesessionid=AE38A38A-25FE...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://pc-dong.github.io/\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"Reactor模式解析及java实现\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"reactor\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"nio\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2022-11-23T00:00:00.000Z\"}]]},\"excerpt\":\"\",\"headers\":[{\"level\":2,\"title\":\"实践DDD中常见问题\",\"slug\":\"实践ddd中常见问题\",\"link\":\"#实践ddd中常见问题\",\"children\":[]},{\"level\":2,\"title\":\"理想的面向对象模型\",\"slug\":\"理想的面向对象模型\",\"link\":\"#理想的面向对象模型\",\"children\":[]},{\"level\":2,\"title\":\"什么是Smart Domain Pattern\",\"slug\":\"什么是smart-domain-pattern\",\"link\":\"#什么是smart-domain-pattern\",\"children\":[]},{\"level\":2,\"title\":\"以数据抽象行为\",\"slug\":\"以数据抽象行为\",\"link\":\"#以数据抽象行为\",\"children\":[{\"level\":3,\"title\":\"默认间接异步获取\",\"slug\":\"默认间接异步获取\",\"link\":\"#默认间接异步获取\",\"children\":[]}]},{\"level\":2,\"title\":\"Smart Domain建模步骤\",\"slug\":\"smart-domain建模步骤\",\"link\":\"#smart-domain建模步骤\",\"children\":[]},{\"level\":2,\"title\":\"Smart Domain实现步骤\",\"slug\":\"smart-domain实现步骤\",\"link\":\"#smart-domain实现步骤\",\"children\":[]},{\"level\":2,\"title\":\"分层架构\",\"slug\":\"分层架构\",\"link\":\"#分层架构\",\"children\":[]},{\"level\":2,\"title\":\"上下文介绍\",\"slug\":\"上下文介绍\",\"link\":\"#上下文介绍\",\"children\":[]},{\"level\":2,\"title\":\"通过Smart Domain对AB实验服务建模\",\"slug\":\"通过smart-domain对ab实验服务建模\",\"link\":\"#通过smart-domain对ab实验服务建模\",\"children\":[]},{\"level\":2,\"title\":\"实现\",\"slug\":\"实现\",\"link\":\"#实现\",\"children\":[]}],\"readingTime\":{\"minutes\":6.83,\"words\":2049},\"filePathRelative\":\"posts/reactor/reactor模式 copy.md\",\"localizedDate\":\"November 23, 2022\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
