export const pagesRoutes = [
  ["v-8daa1a0e","/",{"t":"首页","i":"home","y":"h","e":"[//]: # (This is a blog home page demo.) [//]: # () [//]: # (To use this layout, you should set both layout: Blog and home: true in the page front matter.) [//]: # () [//]: # (F...","r":{"minutes":0.65,"words":196}},["/index.html","/README.md"]],
  ["v-184f4da6","/intro.html",{"t":"自我介绍","i":"info","y":"a","e":"Hi 👋, I'm Peichao Dong A Backend developer from China Connect with me: 716141442@qq.com Languages and Tools: &nbsp;","r":{"minutes":2.45,"words":736}},["/intro","/intro.md"]],
  ["v-d00c1b28","/posts/ddd/smartdomain.html",{"t":"AB测试服务及基于Smart Domain的领域模型设计与实现","i":"edit","y":"a","e":"周末看到徐昊老师在极客时间上的《如何使用Smart Domain实现DDD》 (https://www.bilibili.com/video/BV1QT411J7jh?mid=349471258&p=1&sharefrom=ugc&sharemedium=iphone&shareplat=ios&sharesessionid=AE38A38A-25FE...","d":"2022-11-23T00:00:00.000Z","l":"November 23, 2022","c":["DDD"],"g":["ddd","smart domain"],"r":{"minutes":6.86,"words":2057}},["/posts/ddd/smartdomain","/posts/ddd/smartdomain.md"]],
  ["v-487cc656","/posts/reactor/Java_Socket_01_blocking_IO.html",{"t":"Java Socket编程01 - 阻塞IO","i":"edit","y":"a","e":"本系列文章式响应式学习之旅的网络篇系列文章，响应式一大特性是异步非阻塞，网络通信方面更是如此，本系列文章将从最基本的网络编程开始，逐步探索异步非组塞网络框架底层基本概念原理和应用。 说起网络编程，不得不提两个基本概念：网络IO和Socket (https://en.wikipedia.org/wiki/Network_socket)。网络IO是指计算机...","d":"2022-11-23T00:00:00.000Z","l":"November 23, 2022","c":["响应式编程"],"g":["java","nio"],"r":{"minutes":6.34,"words":1901}},["/posts/reactor/Java_Socket_01_blocking_IO","/posts/reactor/Java_Socket_01_blocking_IO.md"]],
  ["v-311e6732","/posts/rsocket/1.html",{"t":"通过自定义注解实现REST风格的RSocket CRUD应用","i":"edit","y":"a","e":"背景 RSocket (https://rsocket.io/)是一种新的应用层二进制的点对点通信协议，被认为比HTTP更适合于微服务应用 (https://www.infoq.com/articles/give-rest-a-rest-rsocket/)。基于Reactive Streams规范设计，具有双向异步通信、多路复用、消息驱动、支持应用层背...","d":"2022-11-22T00:00:00.000Z","l":"November 22, 2022","c":["RSocket"],"g":["rsocket"],"r":{"minutes":6.15,"words":1846}},["/posts/rsocket/1","/posts/rsocket/1.md"]],
  ["v-2db4b5f4","/posts/rsocket/2.html",{"t":"使用Jmeter Java Request进行RSocket接口性能测试","i":"edit","y":"a","e":"背景 上一篇博客《通过自定义注解实现REST风格的RSocket CRUD应用》 (1.md)介绍了在Spring如何开发RSocket应用，由于RSocket是不同于Http的新的通信协议，目前常见的压测工具都没有提供现成性能测试支持。 Jmeter中提供了Java Request压测方式，可以对Java方法进行压测，我们可以在Java方法中实现RS...","d":"2022-11-23T00:00:00.000Z","l":"November 23, 2022","c":["RSocket"],"g":["rsocket","jmeter","性能测试"],"r":{"minutes":2.96,"words":887}},["/posts/rsocket/2","/posts/rsocket/2.md"]],
  ["v-3706649a","/404.html",{"t":"","y":"p"},["/404"]],
  ["v-5bc93818","/category/",{"t":"Category","y":"p"},["/category/index.html"]],
  ["v-744d024e","/tag/",{"t":"Tag","y":"p"},["/tag/index.html"]],
  ["v-e52c881c","/article/",{"t":"Articles","y":"p"},["/article/index.html"]],
  ["v-75ed4ea4","/encrypted/",{"t":"Encrypted","y":"p"},["/encrypted/index.html"]],
  ["v-d804e652","/slide/",{"t":"Slides","y":"p"},["/slide/index.html"]],
  ["v-154dc4c4","/star/",{"t":"Star","y":"p"},["/star/index.html"]],
  ["v-01560935","/timeline/",{"t":"Timeline","y":"p"},["/timeline/index.html"]],
  ["v-65ee64e3","/category/ddd/",{"t":"DDD Category","y":"p"},["/category/ddd/index.html"]],
  ["v-b313b7ce","/tag/ddd/",{"t":"ddd Tag","y":"p"},["/tag/ddd/index.html"]],
  ["v-ac4d35d0","/category/%E5%93%8D%E5%BA%94%E5%BC%8F%E7%BC%96%E7%A8%8B/",{"t":"响应式编程 Category","y":"p"},["/category/响应式编程/","/category/%E5%93%8D%E5%BA%94%E5%BC%8F%E7%BC%96%E7%A8%8B/index.html"]],
  ["v-8819df4e","/tag/smart-domain/",{"t":"smart domain Tag","y":"p"},["/tag/smart-domain/index.html"]],
  ["v-2a3d6a82","/category/rsocket/",{"t":"RSocket Category","y":"p"},["/category/rsocket/index.html"]],
  ["v-28a1d8bf","/tag/java/",{"t":"java Tag","y":"p"},["/tag/java/index.html"]],
  ["v-b30a782e","/tag/nio/",{"t":"nio Tag","y":"p"},["/tag/nio/index.html"]],
  ["v-55c69eb8","/tag/rsocket/",{"t":"rsocket Tag","y":"p"},["/tag/rsocket/index.html"]],
  ["v-c9ba8ebc","/tag/jmeter/",{"t":"jmeter Tag","y":"p"},["/tag/jmeter/index.html"]],
  ["v-0ece2eb4","/tag/%E6%80%A7%E8%83%BD%E6%B5%8B%E8%AF%95/",{"t":"性能测试 Tag","y":"p"},["/tag/性能测试/","/tag/%E6%80%A7%E8%83%BD%E6%B5%8B%E8%AF%95/index.html"]],
]
